// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scagutbejvgicmllzqge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjYWd1dGJlanZnaWNtbGx6cWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NDIyOTAsImV4cCI6MjA2ODAxODI5MH0.ucTpjt5DZhs6qzMF_IFEekWhgo0gAJrIPSKeGK9Mdss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});